spring.datasource.url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 12345678
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  param:
    captcha:
      width: 100
      height: 35
      deletePeriod: 3600
blog:
  info:
    title: DevPub
    subtitle: Рассказы разработчиков
    phone: +7 903 666-44-55
    email: mail@mail.ru
    copyright: Есипов Сергей
    copyrightFrom: 2020
