spring.datasource.url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 12345678
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect